storage: mysql
allow-command-block: false
disable-wildcard-permissions: false
connection:
  host: localhost
  port: 3306
  database: permissify
  username: permissify
  password: magicalpassword
  file: permissify.db