name: Permissify
version: 1.0.1
authors: [Innectic]
description: Permissify is a dead-simple, next-generation permission plugin.
main: me.innectic.permissify.spigot.PermissifyMain

commands:
    permissify:
        description: Do things with permissions
    perm:
        description: Alias of permissify